### ISSUE TITLE
Where is class WidgetsBaseAdmin defined?

### ISSUE THREAD

**Issue by chellem** [MKhalidJunaid/Sonata-media-upload-multiple-images#1]
Hello, I am looking at your example in Admin classes, both FooterWidgetsAdmin and  FooterWidgetsHasMediaAdmin extends WidgetsBaseAdmin class, but WidgetsBaseAdmin is not there.

Kind regards,
Chellem

**Comment by MKhalidJunaid** [comment]
Hi chellem `WidgetsBaseAdmin` has nothing special in it ,it just extends sonata's main `Admin` class i have created this base admin because i have some common stuff for my admin classes but you can write your own 

```
namespace Traffic\WidgetsBundle\Admin;

use Sonata\AdminBundle\Admin\Admin;
use Sonata\AdminBundle\Show\ShowMapper;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
class WidgetsBaseAdmin extends Admin
{
    /**
     * @param string $code
     * @param string $class
     * @param string $baseControllerName
     */
    public function __construct($code, $class, $baseControllerName)
    {
        parent::__construct($code, $class, $baseControllerName);
    }

}

Regards
```

**Comment by chellem** [comment]
I thought it contained things for making the multiple upload.
Thanks for the explanation.

Kind regards.
